# Site settings
title: Jennifer Blight
blog_title: Soliloquy
blog_url: /blog/

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jgblight.github.io" # the base hostname & protocol for your site
twitter_username: jenblight
github_username:  jgblight

main_image: "/assets/compass.jpg"

# Build settings
markdown: kramdown
